### ISSUE TITLE
Type check quiz_id for bought/notbought

### ISSUE THREAD

**Issue by Mark-Jung** [PerfDevTeam/perf_back#12]
quiz_id should only be integers that are non-negative.

**Comment by Mark-Jung** [comment]
Also, display quiz_id for GET.

**Comment by jameswhang** [comment]
@yulheekim 
FYI: You can type-check an object in python like this:

```
a = "some_string"
type(a)
```

A better way to do it though, is using ```isinstance```:

```
import types
print isinstance('a', types.StringType)    #this will print "True"
```

**Comment by Mark-Jung** [comment]
@yulheekim Remember to close the issue with the reference to the pull request after you have finished the issue.
