### ISSUE TITLE
Add an endpoint for querying all purchases made by a user

### ISSUE THREAD

**Issue by jameswhang** [PerfDevTeam/perf_back#14]
Add an endpoint that returns all the purchases made by a user by querying the "bought" table. 

HTTP Method: GET
API endpoint: /purchases/bought/{user_email}

Example:
```
$.post(API_ENDPOINT+'/purchases/bought/san2017@u.northwestern.edu', function(res) {
    console.log(res);
});
```

should print all purchases made by the user with email "san2017@u.northwestern.edu".

**Comment by Mark-Jung** [comment]
Missing testing.

**Comment by jameswhang** [comment]
@myidsan Pls write test for this endpoint
