### ISSUE TITLE
Add chronological ordering to /bought/all and /notbought/all

### ISSUE THREAD

**Issue by Mark-Jung** [PerfDevTeam/perf_back#15]
The output of /bought/all currently is just a dump. Juno wants it to be chronologically ordered.
This can be done by either sorting the output by the id or the date created. I recommend doing it by id.

The sort is greatest to lowest btw.

**Comment by jameswhang** [comment]
Fixed with https://github.com/PerfDevTeam/perf_back/commit/1b175dba897989bfe02096722824b5d87d91ec1a and https://github.com/PerfDevTeam/perf_back/commit/c53190506b39e8f0ea408333c1b3120b2a1d7666
