### ISSUE TITLE
Remove dependency on Flask-RESTful

### ISSUE THREAD

**Issue by jameswhang** [PerfDevTeam/perf_back#19]
Too much dependency on a library does not help with the overall architecture. Open to discussions but I think Flask-RESTful poses too much restrictions on the way resources are allocated. It might be good for simplistic APIs like the ones we currently have, but as we add more complex APIs it might become a bottleneck and mess up our code. @Mark-Jung thoughts?

**Comment by Mark-Jung** [comment]
Haven't thought about it until you mentioned it, but I think you have a valid point. Removing the dependency of what we have right now would only essentially require us to do 2 things:

1. No more Resources. (Can be replaced by the endpoint decorator in Flask)
2. No more reqparse so we need to come up with our own request parser/error handler.

Flask itself should be enough to handle what we want. If we want to move to a wholly another framework, I think that would cost us too much time and resources.

**Comment by jameswhang** [comment]
Yeah, I agree moving to another framework is too much work (Although if you rewrite it from scratch it won't be an issue :p )

reqparse shouldn't be too hard anyway. We can just write a better one that has type checking + stuff. Also, we should consider switching over to Python3 (3.6 in particular) since it has built-in support for type checking.

**Comment by Mark-Jung** [comment]
Oh this is already in Python3.6. And rewriting from scratch... hmmm.... Do we have to? I maybe wrong but I don't see the reason to currently.
