### ISSUE TITLE
Add Stripe support

### ISSUE THREAD

**Issue by Mark-Jung** [PerfDevTeam/perf_back#27]
https://stripe.com/docs/checkout

need backend support for stripe.

**Comment by jameswhang** [comment]
@Mark-Jung who's taking this item?

**Comment by Mark-Jung** [comment]
Or you can. Or @myidsan can. But San is pretty occupied with design and paper prototyping. I'll probably get on this after quiz support.(July 3rd?)

**Comment by jameswhang** [comment]
I'm already working on quiz.. Wanna collaborate on my branch?

**Comment by Mark-Jung** [comment]
awesome. I'll look at it in a moment.

**Comment by jameswhang** [comment]
https://github.com/PerfDevTeam/perf_back/tree/quiz

**Comment by myidsan** [comment]
I started on this an hour ago. I'll take it
