### ISSUE TITLE
Card, NotBought, Bought Additions

### ISSUE THREAD

**Issue by Mark-Jung** [PerfDevTeam/perf_back#3]
1. Put(edit) Card
2. Delete Card
3. Delete NotBought, Bought(by name,)

**Comment by Mark-Jung** [comment]
4. Disallow duplicate creation of Card

**Comment by Mark-Jung** [comment]
1 is done

**Comment by jameswhang** [comment]
@Mark-Jung  Still relevant?

**Comment by Mark-Jung** [comment]
Not Really. It can be closed. I can just edit the bought and notbought directly.
