### ISSUE TITLE
Collecting data from quiz completion

### ISSUE THREAD

**Issue by Mark-Jung** [PerfDevTeam/perf_back#31]
To test out how sane the quiz logic is, we want to collect ALL data. Now, all the answer choices from the quiz will be going to the server, where none of the quiz logic, not even adding up points, will happen in the website. The server will log the quiz answers and generate the answer from the quiz logic.

**Comment by jameswhang** [comment]
What exact "data" are we talking about here?

**Comment by myidsan** [comment]
POST /quiz/result support this feature. Check out the 'official' documentation.
