### ISSUE TITLE
add PUT method to /quiz

### ISSUE THREAD

**Issue by myidsan** [PerfDevTeam/perf_back#35]
There should be a way to fix quiz, quizcard, quizquestions table when the images are added.

**Comment by Mark-Jung** [comment]
How about we make another param in the current spreadsheet.py, where the first param is the mode you want to do(1.post 2.put) and for put just take in the whole quiz and update ever single field for it?

**Comment by jameswhang** [comment]
Don't do mode please... Just make it a separate func. Using mode hurts the readability.

**Comment by Mark-Jung** [comment]
no no not on the main code zzzz i'm talking about the python script san wrote

**Comment by jameswhang** [comment]
whatever code it is... Always make code maintainable. If it's a one time script that you'll run ONLY ONCE, then sure. Do whatever jank shit you want. But if you are gonna keep on changing and using that code then please make it maintainable.

**Comment by myidsan** [comment]
lol. are we trying to use the same script file for all endpoints? If so, we have to differentiate it by end point for different JSON format also.

**Comment by jameswhang** [comment]
@myidsan When you say "There should be a way to fix quiz, quizcard, quizquestions table when the images are added." , do you mean you want the ability to edit the rows in the db for these models after they've been created?

**Comment by Mark-Jung** [comment]
I assumed so

**Comment by myidsan** [comment]
yes and I want them to be easy as fixing a spreadsheet data and running a script after that.

**Comment by sywhang** [comment]
Got it. Using the same script is fine. Don't do it using 'mode'. Just make a separate func in spreadsheet.py that POSTs to a different endpoint. Perhaps /quiz/edit.

**Comment by jameswhang** [comment]
Got it. Using the same script is fine. Don't do it using 'mode'. Just make a separate func in spreadsheet.py that POSTs to a different endpoint. Perhaps /quiz/edit.

**Comment by myidsan** [comment]
okay. The params for the script will be `baseurl, endpoint, method, name_of_spreadsheet_to_update`. lmk if there are other better ideas.

**Comment by jameswhang** [comment]
> The params for the script will be

You mean params for the function?

**Comment by myidsan** [comment]
params for the script itself so it can be fed into the function inside

**Comment by jameswhang** [comment]
> you are right with your assumption

Not an assumption. Just reading the code :) 

> have the same script and use multiple params

This is better. You just need one additional parameter to the ones I mentioned above. 

My main concern now is that the whole thing just seems jank. You want the ability to add / modify / delete existing data from the database, so you have this awkward one way sync thing where you have to update the Google Spreadsheet, then run this script to reflect it on the db... Which means that the actual db is the Spreadsheet and our production db is some sort of cache. 

Making an admin site to do all these would be a best long term goal that we should be working towards, before mindlessly adding these scripts to perform these jobs...

**Comment by myidsan** [comment]
> Not an assumption. Just reading the code :)
👍 
Overall understood. Script was supposed to be useful for testing and quick updates. We are trying to make the new quiz page live by end of this week. After that, we will implement the necessary tools. Thanks!
