### ISSUE TITLE
add endpoint for adding accords

### ISSUE THREAD

**Issue by myidsan** [PerfDevTeam/perf_back#36]
We need a way to add accords into the database. It will be similar to what we are currently doing with quiz but much simpler.

**Comment by Mark-Jung** [comment]
Why do we need to add accords again?

**Comment by myidsan** [comment]
We need individual accord data to go through current quiz logic. Currently, we compare the aggregated result of the quiz to each accord and sort them in descending order for matching.

**Comment by Mark-Jung** [comment]
and now we don't do the scent profiles? Previously, our accords were matched 1 to 1 with a scent profile. Is that going to change?

**Comment by myidsan** [comment]
done
