### ISSUE TITLE
price should goes until 100th precision only.

### ISSUE THREAD

**Issue by Mark-Jung** [PerfDevTeam/perf_back#45]
as stated in the title, price should go until 100th precision only. this will be relevant for all models that has some relation to money (ex: payment, bottle)

**Comment by jameswhang** [comment]
People. Floats are expensive. Just because we use Python it doesn't mean we get to do floating point operations for free. Use integers whenever possible. Is there any benefit on doing floating point arithmetic? I assume you all took 213. Please don't ask why it's more expensive.

**Comment by Mark-Jung** [comment]
yayyyyy we can use cents as unit and have integer!!

**Comment by myidsan** [comment]
okay makes more sense. I'll update the bottles branch and do another pr
